// react-app/src/components/Messages.jsx
import { useEffect, useState, createContext, useContext } from "react";
import { MessageContext } from "./MessageContext";
// import useMessages from "../models/messages.ts";

export default function Messages() {
  const messages = useContext(MessageContext);
  const [isOpen, setIsOpen] = useState(false);

  useEffect(() => {
    messages.add({ type: "info", message: "Hello, world!" });
  }, []);

  return (
    <div
      class={`navbar-item has-dropdown notification-component ${
        isOpen && "is-active"
      }`}
    >
      <a class="navbar-link" onClick={() => setIsOpen(!isOpen)}>
        {" "}
        {/*this can be a named function to call */}
        <span class="icon">
          <i class="fas fa-bell"></i>
        </span>
        {messages.notifications.length && (
          <span class="tag is-danger">{messages.notifications.length}</span>
        )}
      </a>
      <div class="navbar-dropdown">
        {messages.notifications.map((x, i) => (
          <div class={`notification is-light is-${x.type}`} key={i}>
            <button class="delete" onClick={() => messages.close(i)}></button>
            {x.message}
          </div>
        ))}
      </div>
    </div>
  );
}

export const MessagesContext = createContext({});

// client/src/components/Messages.vue
<script setup lang="ts">
import { ref } from "vue";
import { useMessages } from "../models/messages";
const messages = useMessages();
const isOpen = ref(false);
</script>

<template>
  <div class="navbar-item has-dropdown" :class="{ 'is-active': isOpen }">
    <a class="navbar-link" @click="isOpen = !isOpen">
      <span class="icon">
        <i class="fas fa-bell"></i>
      </span>
      <span class="tag is-danger" v-if="messages.notifications.length">
        {{ messages.notifications.length }}
      </span>
    </a>
    <div class="navbar-dropdown">
      <div
        v-for="(x, i) in messages.notifications"
        :class="`notification is-light is-${x.type}`"
      >
        <button class="delete" @click="messages.close(i)"></button>
        {{ x.message }}
      </div>
    </div>
  </div>
</template>

<style scoped>
.icon {
  font-size: 1.5em;
}
.navbar-dropdown {
  width: max-content;
  max-width: 300px;
}
.notification {
  margin: 0.5rem;
  width: 100%;
}
.tag {
  position: absolute;
  font-size: 0.8em;
  top: 0.5em;
  right: 2.5em;
  height: 1.5em;
  padding: 0.5em;
  border-radius: 50%;
}
</style>
